/*
modulo: "PLCPinturaPo", // Módulo para acesso dos sinais -> Ex: PLCPinturaPo, PLCecoat, WISE1
endereco: "Global.recEstufaPP", // Endereço do sinal desejado
casasDec: 0, // Quantidade de casas decimais (se houver) - null (não utiliza);
valor: null, // Valor de inicialização
cor: "lightgreen", // Valor de cor inicial (se utilizar)
escala: 0.3,  // Valor para escala entre o valor recebido e o valor disponibilizado

// OPÇÕES DE ALERTA
// Alerta por Mínimo e Máximo
min2: "min2_Agua", // Valor limite mínimo para indicação de FALHA
min1: "min1_Agua", // Valor limite mínimo para indicação de ALERTA
max1: "max1_Agua", // Valor limite máximo para indicação de ALERTA
max2: "max2_Agua", // Valor limite máximo para indicação de FALHA

// Alerta por histerese
SetPoint: "SP_Fosfato", // Setpoint de controle da variável
hist_func: "Hfunc_Fosfato", // Tamanho da variável de histerese de funcionamento (fora desta faixa indica alerta)
hist_falha: "Hfalha_Fosfato", // Tamanho da variável de histerese para Falha (fora desta faixa indica FALHA)

condBD: "=== true", // Condição de disparo para inserir no Banco de Dados - Ex: True, False, > 130, etc..
borda: false, // Se utilizar a borda para contagem do tempo para inclusão no Banco de dados -> se False, o tempo = condBD
datHraUltDisp: null, // Registro do disparo da condição para inclusão no Banco de Dados (condBD)
tmpCondBD: null, // Uso do sistema - tempo em condições para gravação no Banco de Dados (condBD)
periodoBD: 0, // Período para inclusão no Banco de dados - "0" => disparo conforme "condBD"; "null" => não grava em BD
periodoAq: "15", // Período para monitoração da variável no CLP ou Módulo
maxBD: 30, // Tempo para permanencia dos dados no BD em dias
maxV: 100 // Valor máximo para os valores de leitura (em caso de ultrapassagem deste valor, será apresentado "Max")

mensagem: "Nível de água muito baixo. Caixa d´água do Refeitório", // Mensagem de falha para aviso por e-mail, telefone, supervisorio
flagAviso: false, // Flag auxiliar para uso do software
avisar: [
            { nome: "Martins", sms: false, telefone: true, email: true }, // informações dos contatos para envio de alertas
            { nome: "Jardim", sms: false, telefone: true, email: true },
            { nome: "Gustavo2", sms: false, telefone: true, email: true },
            { nome: "William", sms: false, telefone: true, email: true },
        ],

*/


var Variaveis = {
    // ******************** Pintura pó e líquida **************************
    // Receitas Pintura Pó
    recEstufaPP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.recEstufaPP",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        periodoAq: "15",
    },
    aFilaPP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.aFilaPP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "15",
    },
    aPosRecPP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.aPosRecPP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "15",
    },
    // Receitas Pintura Líquida
    recEstufaPL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.recEstufaPL",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        periodoAq: "15",
        maxBD: 120,
    },
    aFilaPL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.aFilaPL",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "15",
    },
    aPosRecPL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.aPosRecPL",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "15",
    },
    // Velocidade das monovias
    velMonoviaPL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.velMonoviaPL",
        casasDec: 2,
        valor: null,
        cor: "lightgreen",
        periodoBD: 15,
        periodoAq: "15",
        maxBD: 120,
    },
    velMonoviaPP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.velMonoviaPP",
        casasDec: 2,
        valor: null,
        cor: "lightgreen",
        periodoBD: 15,
        periodoAq: "15",
        maxBD: 120,
    },
    stsMonoviaPP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.stsMonoviaPP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== false",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "15",
        maxBD: 120,
    },
    stsVelMonovPP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.flhVelMonov_PP",
        casasDec: null,
        valor: null,
        cor: "",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "15",
        maxBD: 120,
    },
    stsMonoviaPL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.stsMonoviaPL",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== false",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "15",
        maxBD: 120,
    },
    // Temperatura atual dos queimadores
    temperQueim1PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[0]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 30,
        periodoAq: "30",
        maxBD: 120,
    },
    temperQueim2PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[1]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 30,
        periodoAq: "30",
        maxBD: 120,
    },
    temperQueim3PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[2]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 30,
        periodoAq: "30",
        maxBD: 120,
    },
    temperQueim4PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[3]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 30,
        periodoAq: "30",
        maxBD: 120,
    },
    temperQueim1PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[4]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 30,
        periodoAq: "30",
        maxBD: 120,
    },
    temperQueim2PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[5]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 30,
        periodoAq: "30",
        maxBD: 120,
    },
    // Setpoint dos queimadores
    spQueim1PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[6]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        periodoAq: "30",
        maxBD: 120,
    },
    spQueim2PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[7]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        periodoAq: "30",
        maxBD: 120,
    },
    spQueim3PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[8]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        periodoAq: "30",
        maxBD: 120,
    },
    spQueim4PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[9]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        periodoAq: "30",
        maxBD: 120,
    },
    spQueim1PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[10]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        periodoAq: "30",
        maxBD: 120,
    },
    spQueim2PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Output_Registers[11]",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        periodoAq: "30",
        maxBD: 120,
    },
    // Sinais dos ventiladores
    leitVent1PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[0]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitVent2PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[1]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitVent3PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[2]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitVent4PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[3]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitVent1PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[4]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
    },
    leitVent2PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[5]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    // Sinais dos queimadores
    leitQuem1PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[6]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitQuem2PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[7]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitQuem3PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[8]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitQuem4PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[9]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitQuem1PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[10]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitQuem2PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[11]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitCortArPP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[36]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },
    leitCortArPL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[37]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: null,
        periodoAq: "30",
    },

    // Sinalização de falhas QUEIMADORES
    falhaQuem1PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[12]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaQuem2PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[13]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaQuem3PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[14]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaQuem4PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[15]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaQuem1PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[16]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaQuem2PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[17]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    // Sinalização de falhas QUEIMADORES
    falhaVent1PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[24]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaVent2PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[25]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaVent3PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[26]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaVent4PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[27]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaVent1PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[28]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaVent2PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[29]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    // Sinalização de falhas de temperatura
    falhaTemp1PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[30]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaTemp2PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[31]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaTemp3PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[32]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaTemp4PP: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[33]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaTemp1PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[34]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    falhaTemp2PL: {
        modulo: "PLCPinturaPo",
        endereco: "Global.mb_Input_Coils[35]",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 120,
    },
    // Sinais das chamas dos queimadores
    Queim1PPchmBx: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaBaixa_Q1_PP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim1PPchmAt: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaAlta_Q1_PP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim2PPchmBx: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaBaixa_Q2_PP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim2PPchmAt: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaAlta_Q2_PP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim3PPchmBx: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaBaixa_Q3_PP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim3PPchmAt: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaAlta_Q3_PP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim4PPchmBx: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaBaixa_Q4_PP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim4PPchmAt: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaAlta_Q4_PP",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim1PLchmBx: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaBaixa_Q1_PL",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim1PLchmAt: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaAlta_Q1_PL",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim2PLchmBx: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaBaixa_Q2_PL",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },
    Queim2PLchmAt: {
        modulo: "PLCPinturaPo",
        endereco: "Entradas_Saidas.O_chamaAlta_Q2_PL",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 60,
    },

    // ******************** Nível de água **************************
    // Nível de água da caixa de água do estacionamento
    min1_Agua: {
        modulo: "PLCecoat",
        endereco: "Global.MIN1_NIVEL_AGUA",
        casasDec: null,
        valor: null,
    },
    min2_Agua: {
        modulo: "PLCecoat",
        endereco: "Global.MIN2_NIVEL_AGUA",
        casasDec: null,
        valor: null,
    },

    nivel_Agua: {
        modulo: "PLCecoat",
        endereco: "Global.Nivel_Cx_Agua",
        casasDec: 1,
        valor: null,
        min2: "min2_Agua",
        min1: "min1_Agua",
        max1: "max1_Agua",
        max2: "max2_Agua",
        cor: "lightgreen",
        periodoBD: 300,
        periodoAq: "30",
        maxBD: 60,
    },
    

    //Nível de água da caixa de água do Refeitório
    min1_Ag_Ref: {
        modulo: null,
        endereco: null,
        casasDec: null,
        valor: 35,
    },
    min2_Ag_Ref: {
        modulo: null,
        endereco: null,
        casasDec: null,
        valor: 25,
    },
    nivel_Ag_Ref: {
        modulo: "WISE1",
        endereco: 0,
        casasDec: 1,
        escala: 0.3,
        valor: null,
        mensagem: "Nível de água muito baixo. Caixa d´água do Refeitório",
        flagAviso: false,
        avisar: [
            { nome: "Martins", sms: false, telefone: true, email: true },
            { nome: "Jardim", sms: false, telefone: true, email: true },
            { nome: "Gustavo2", sms: false, telefone: true, email: true },
            { nome: "William", sms: false, telefone: true, email: true },
        ],
        min2: "min2_Ag_Ref",
        min1: "min1_Ag_Ref",
        max1: null,
        max2: null,
        cor: "lightgreen",
        periodoBD: 300,
        condBD: "< 25",
        condRet: "> 25",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10000",
        maxBD: 60,
    },
    /*
    falhaNvlAguaRf: {
        modulo: "WISE1",
        endereco: 0,
        escala: 0.3,
        valor: null,
        mensagem: "Nível de água muito baixo. Caixa d´água do Refeitório",
        flagAviso: false,
        avisar: [
            { nome: "Martins", sms: false, telefone: true, email: true },
            { nome: "Jardim", sms: false, telefone: true, email: true },
            { nome: "Gustavo2", sms: false, telefone: true, email: true },
            { nome: "William", sms: false, telefone: true, email: true },
        ],
        periodoBD: 0,
        condBD: "< 25",
        condRet: "> 25",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "3000",
        maxBD: 60,
    },
*/

    // ***************************************************************
    // ******************** Linha do E-coat **************************
    // ***************************************************************
    // Produtividade do E-coat
    cicloEcoat: {
        modulo: "PLCecoat",
        endereco: "Entradas_Saidas.O_Ciclo_Peca_MCP",
        casasDec: null,
        valor: null,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: true,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },
    bastPerdido: {
        modulo: "PLCecoat",
        endereco: "Global.AUX_FALTA_BAST",
        casasDec: null,
        valor: null,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        flagAviso: false,
        borda: true,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },
    // Temperatura atual da estufa do E-coat
    SP_EntEstfEcoat: {
        modulo: "PLCecoat",
        endereco: "Global.TMPR_ENTR_ESTF",
        casasDec: null,
        valor: null,
    },

    Hfunc_EntEstfEcoat: {
        modulo: "PLCecoat",
        endereco: "Global.HSTE_TMPR_ESTF",
        casasDec: null,
        valor: null,
    },

    Hfalha_EntEstfEcoat: {
        modulo: "PLCecoat",
        endereco: "Global.HSTE_FLHTP_ESTF",
        casasDec: null,
        valor: null,
    },

    temperEntEstEcoat: {
        modulo: "PLCecoat",
        endereco: "Global.Temperatura_EntEstufa",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 30,
        periodoAq: "30",
        maxBD: 120,
        SetPoint: "SP_EntEstfEcoat",
        hist_func: "Hfunc_EntEstfEcoat",
        hist_falha: "Hfalha_EntEstfEcoat",
    },

    SP_SaiEstfEcoat: {
        modulo: "PLCecoat",
        endereco: "Global.TMPR_SAID_ESTF",
        casasDec: null,
        valor: null,
    },

    Hfunc_SaiEstfEcoat: {
        modulo: "PLCecoat",
        endereco: "Global.HSTS_TMPR_ESTF",
        casasDec: null,
        valor: null,
    },
    Hfalha_SaiEstfEcoat: {
        modulo: "PLCecoat",
        endereco: "Global.HSTS_FLHTP_ESTF",
        casasDec: null,
        valor: null,
    },
    temperSaiEstEcoat: {
        modulo: "PLCecoat",
        endereco: "Global.Temperatura_SaiEstufa",
        casasDec: 0,
        valor: null,
        cor: "lightgreen",
        periodoBD: 30,
        periodoAq: "30",
        maxBD: 120,
        SetPoint: "SP_SaiEstfEcoat",
        hist_func: "Hfunc_SaiEstfEcoat",
        hist_falha: "Hfalha_SaiEstfEcoat",
    },
    // Temperatura atual do KTL
    SP_KTL: {
        modulo: "PLCecoat",
        endereco: "Global.TMPR_KTL",
        casasDec: null,
        valor: null,
    },
    Hfunc_KTL: {
        modulo: "PLCecoat",
        endereco: "Global.HST_TMPR_KTL",
        casasDec: null,
        valor: null,
    },
    Hfalha_KTL: {
        modulo: "PLCecoat",
        endereco: "Global.HST_FLHTP_KTL",
        casasDec: null,
        valor: null,
    },
    tmp_KTL: {
        modulo: "PLCecoat",
        endereco: "Global.Temperatura_KTL",
        casasDec: 1,
        valor: null,
        SetPoint: "SP_KTL",
        hist_func: "Hfunc_KTL",
        hist_falha: "Hfalha_KTL",
        cor: "lightgreen",
        periodoBD: 1500,
        periodoAq: "15",
        maxBD: 30,
    },

    //Temperatura atual da Caldeira
    SP_Cald: {
        modulo: "PLCecoat",
        endereco: "Global.TMPR_CALD",
        casasDec: null,
        valor: null,
    },
    Hfunc_Cald: {
        modulo: "PLCecoat",
        endereco: "Global.HST_TMPR_CALD",
        casasDec: null,
        valor: null,
    },
    Hfalha_Cald: {
        modulo: "PLCecoat",
        endereco: "Global.HST_FLHTP_CALD",
        casasDec: null,
        valor: null,
    },
    tmp_Cald: {
        modulo: "PLCecoat",
        endereco: "Global.Temperatura_Caldeira",
        casasDec: 1,
        valor: null,
        SetPoint: "SP_Cald",
        hist_func: "Hfunc_Cald",
        hist_falha: "Hfalha_Cald",
        cor: "lightgreen",
        periodoBD: 300,
        periodoAq: "15",
        maxBD: 30,
        maxV: 200
    },

    // Temperatura atual do tanque de Ácido 1
    SP_Acido1: {
        modulo: "PLCecoat",
        endereco: "Global.TMPR_TA1",
        casasDec: null,
        valor: null,
    },
    Hfunc_Acido1: {
        modulo: "PLCecoat",
        endereco: "Global.HST_TMPR_TA1",
        casasDec: null,
        valor: null,
    },
    Hfalha_Acido1: {
        modulo: "PLCecoat",
        endereco: "Global.HST_FLHTP_TA1",
        casasDec: null,
        valor: null,
    },
    tmp_Acido1: {
        modulo: "PLCecoat",
        endereco: "Global.Temperatura_Acido1",
        casasDec: 1,
        valor: null,
        SetPoint: "SP_Acido1",
        hist_func: "Hfunc_Acido1",
        hist_falha: "Hfalha_Acido1",
        cor: "lightgreen",
        periodoBD: 300,
        periodoAq: "10",
        maxBD: 120,
        maxV: 100
    },

    // Temperatura atual do tanque de Ácido 2
    SP_Acido2: {
        modulo: "PLCecoat",
        endereco: "Global.TMPR_TA2",
        casasDec: null,
        valor: null,
    },
    Hfunc_Acido2: {
        modulo: "PLCecoat",
        endereco: "Global.HST_TMPR_TA2",
        casasDec: null,
        valor: null,
    },
    Hfalha_Acido2: {
        modulo: "PLCecoat",
        endereco: "Global.HST_FLHTP_TA2",
        casasDec: null,
        valor: null,
    },
    tmp_Acido2: {
        modulo: "PLCecoat",
        endereco: "Global.Temperatura_Acido2",
        casasDec: 1,
        valor: null,
        SetPoint: "SP_Acido2",
        hist_func: "Hfunc_Acido2",
        hist_falha: "Hfalha_Acido2",
        cor: "lightgreen",
        periodoBD: 300,
        periodoAq: "10",
        maxBD: 120,
    },

    // Temperatura atual do tanque de Desengraxe 1
    SP_Deseng1: {
        modulo: "PLCecoat",
        endereco: "Global.TMPR_TD1",
        casasDec: null,
        valor: null,
    },
    Hfunc_Deseng1: {
        modulo: "PLCecoat",
        endereco: "Global.HST_TMPR_TD1",
        casasDec: null,
        valor: null,
    },
    Hfalha_Deseng1: {
        modulo: "PLCecoat",
        endereco: "Global.HST_FLHTP_TD1",
        casasDec: null,
        valor: null,
    },
    tmp_Deseng1: {
        modulo: "PLCecoat",
        endereco: "Global.Temperatura_Deseng1",
        casasDec: 1,
        valor: null,
        SetPoint: "SP_Deseng1",
        hist_func: "Hfunc_Deseng1",
        hist_falha: "Hfalha_Deseng1",
        cor: "lightgreen",
        periodoBD: 300,
        periodoAq: "10",
        maxBD: 120,
    },

    // Temperatura atual do tanque de Desengraxe 2
    SP_Deseng2: {
        modulo: "PLCecoat",
        endereco: "Global.TMPR_TD2",
        casasDec: null,
        valor: null,
    },
    Hfunc_Deseng2: {
        modulo: "PLCecoat",
        endereco: "Global.HST_TMPR_TD2",
        casasDec: null,
        valor: null,
    },
    Hfalha_Deseng2: {
        modulo: "PLCecoat",
        endereco: "Global.HST_FLHTP_TD2",
        casasDec: null,
        valor: null,
    },
    tmp_Deseng2: {
        modulo: "PLCecoat",
        endereco: "Global.Temperatura_Deseng2",
        casasDec: 1,
        valor: null,
        SetPoint: "SP_Deseng2",
        hist_func: "Hfunc_Deseng2",
        hist_falha: "Hfalha_Deseng2",
        cor: "lightgreen",
        periodoBD: 300,
        periodoAq: "10",
        maxBD: 120,
    },

    // Temperatura atual do tanque do Fosfato
    SP_Fosfato: {
        modulo: "PLCecoat",
        endereco: "Global.TMPR_TFOSF",
        casasDec: null,
        valor: null,
    },
    Hfunc_Fosfato: {
        modulo: "PLCecoat",
        endereco: "Global.HST_TMPR_TFOSF",
        casasDec: null,
        valor: null,
    },
    Hfalha_Fosfato: {
        modulo: "PLCecoat",
        endereco: "Global.HST_FLHTP_TFOSF",
        casasDec: null,
        valor: null,
    },
    tmp_Fosfato: {
        modulo: "PLCecoat",
        endereco: "Global.Temperatura_Fosfato",
        casasDec: 1,
        valor: null,
        SetPoint: "SP_Fosfato",
        hist_func: "Hfunc_Fosfato",
        hist_falha: "Hfalha_Fosfato",
        cor: "lightgreen",
        periodoBD: 300,
        periodoAq: "10",
        maxBD: 120,
    },

    // ************ Alertas de falhas ********************
    // Falha de nível de água da caixa do Estacionamento

    falha_nivel_Agua: {
        nome: "Nível Água",
        modulo: "PLCecoat",
        endereco: "Global.FALHA_NIVEL_AGUA",
        casasDec: null,
        valor: false,
        mensagem:
            "Nível de água está muito baixo. Caixa d´água externa - estacionamento",
        flagAviso: false,
        avisar: [
            { nome: "Martins", sms: false, telefone: true, email: true },
            { nome: "Jardim", sms: false, telefone: true, email: true },
            { nome: "Gustavo2", sms: false, telefone: true, email: true },
            { nome: "William", sms: false, telefone: true, email: true },
        ],
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "60",
        maxBD: 30,
    },

    // Falha de temperatura no KTL
    falha_tmp_KTL: {
        nome: "Temperatura KTL",
        modulo: "PLCecoat",
        endereco: "Global.FALHA_45",
        casasDec: null,
        valor: false,
        mensagem:
            "Temperatura da tinta do KTL está fora do especificado, avisar a manutenção e ao LQF !!!",
        flagAviso: false,
        avisar: [
            { nome: "Martins", sms: false, telefone: true, email: true },
            { nome: "Jardim", sms: false, telefone: true, email: true },
            { nome: "Gustavo2", sms: false, telefone: true, email: true },
            { nome: "William", sms: false, telefone: true, email: true },
        ],
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 30,
    },

    // Falha Crítica
    falha_Critica: {
        nome: "E-coat",
        modulo: "PLCecoat",
        endereco: "Global.FALHA_CRITICA",
        casasDec: null,
        valor: false,
        mensagem:
            "Falha crítica no e-coat sem tratativa, avisar a manutenção e ao LQF urgente!!!",
        flagAviso: false,
        avisar: [
            { nome: "Portaria", sms: true, telefone: true, email: true },
            { nome: "Portaria2", sms: false, telefone: true, email: false },
            { nome: "Martins", sms: false, telefone: true, email: true },
            { nome: "Jardim", sms: false, telefone: true, email: true },
            { nome: "Gustavo2", sms: false, telefone: true, email: true },
            { nome: "William", sms: false, telefone: true, email: true },
        ],
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "60",
        maxBD: 60,
    },

    // Falha nos módulos IO do E-coat
    falha_IO: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_33",
        casasDec: null,
        valor: false,
        mensagem: "Falha nos módulos I/O do E-coat!!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha de temperatura do painel Geral do E-coat
    falha_TmpPnlGer: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_34",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura no Painel Geral do E-coat!!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha no Painel de Operaçãod o E-coat
    falha_TmpPnlOp: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_35",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura no Painel de Operação do E-coat!!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha de temperatura no painel do Retirifcador do E-coat
    falha_TmpPnlRet: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_36",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura no Painel do Retificador do E-coat!!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha nos ventiladores da estufa do E-coat
    falha_VntEstEcoat: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_37",
        casasDec: null,
        valor: false,
        mensagem: "Falha nos Ventiladores da Estufa do E-coat!!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha no tanque de ácido 1 do E-coat
    falha_Acido1: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_38",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura no Tanque de Ácido 1 !!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha no tanque de ácido 2 do E-coat
    falha_Acido2: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_39",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura no Tanque de Ácido 2 !!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha no tanque de desengraxe 1 do E-coat
    falha_Desg1: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_40",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura no Tanque de Desengraxe 1 !!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha no tanque de desengraxe 2 do E-coat
    falha_Desg2: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_41",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura no Tanque de Desengraxe 2 !!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha no tanque do fosfato do E-coat
    falha_Fosf: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_42",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura no Tanque de Fosfato!!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha de temperatura na entrada da estufa
    falha_TmpEntEst: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_43",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura na Entrada da Estufa do E-coat!!!",
        flagAviso: false,
        flagBD: false,
        periodoBD: 0,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha de temperatura na saída da estufa
    falha_TmpSaiEst: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_44",
        casasDec: null,
        valor: false,
        mensagem: "Falha de temperatura na Saída da Estufa do E-coat!!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha no queimador da entrada da estufa
    falha_QmdEntEst: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_46",
        casasDec: null,
        valor: false,
        mensagem: "Falha no queimador da Entrada da Estufa do E-coat!!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha no queimador da saída da estufa
    falha_QmdSaiEst: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_47",
        casasDec: null,
        valor: false,
        mensagem: "Falha no queimador da Saída da Estufa do E-coat!!!",
        flagAviso: false,
        periodoBD: 0,
        flagBD: false,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },


    // Falha na Caldeira
    falha_Cald: {
        nome: "Caldeira",
        modulo: "PLCecoat",
        endereco: "Global.FALHA_48",
        casasDec: null,
        valor: false,
        mensagem: "Falha na Caldeira!!!",
        flagAviso: false,
        flagBD: false,
        avisar: [
            { nome: "Martins", sms: false, telefone: true, email: true },
            { nome: "Jardim", sms: false, telefone: true, email: true },
            { nome: "Gustavo2", sms: false, telefone: true, email: true },
        ],
        periodoBD: 0,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },



    // TESTE
    falha_Teste: {
        nome: "Teste",
        modulo: "PLCecoat",
        endereco: "Global.FALHA_49",
        casasDec: null,
        valor: false,
        mensagem: "Teste!!!",
        flagAviso: false,
        flagBD: false,
        avisar: [
            { nome: "Gustavo2", sms: false, telefone: false, email: true },
        ],
        periodoBD: 0,
        condBD: "== true",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "10",
        maxBD: 365,
    },

    // Falha no Retificador do E-coat
    falhaRetific: {
        modulo: "PLCecoat",
        endereco: "Global.FALHA_12",
        casasDec: null,
        valor: null,
        cor: "lightgreen",
        periodoBD: 0,
        condBD: "== true",
        flagAviso: false,
        flagBD: false,
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "30",
        maxBD: 365,
    },


    // ***************************************************************
    // ********************* Ar comprimido ***************************
    // ***************************************************************


    //Vazao de Ar Comprimido
    max_VazArComp2: {
        modulo: null,
        endereco: null,
        casasDec: null,
        valor: 1200,
    },
    max_VazArComp1: {
        modulo: null,
        endereco: null,
        casasDec: null,
        valor: 1050,
    },
    vazaoArComp: {
        modulo: "PLCecoat",
        endereco: "Global.QTD_BST_T1",
        casasDec: 1,
        escala: 1,
        valor: null,
        mensagem: "Consumo de ar-comprimido muito alto",
        flagAviso: false,
        avisar: [
            { nome: "Gustavo2", sms: false, telefone: true, email: true }
        ],
        min2: null,
        min1: null,
        max1: "max_VazArComp1",
        max2: "max_VazArComp2",
        cor: "lightgreen",
        periodoBD: 300,
        condBD: ">= 1600",
        condRet: "< 1200",
        borda: false,
        datHraUltDisp: null,
        tmpCondBD: null,
        periodoAq: "15",
        maxBD: 30,
        maxV: 5000
    }

}

exports.Variaveis = Variaveis